version: "3"
services:
  db: 
    image: postgres
    environment:
      POSTGRES_PASSWORD: topsecret
      POSTGRES_USER: user_db
      POSTGRES_DB: cats_db
      POSTGRES_PORT: 5432
  app:
    image: my-techdemo-app
    ports:
      - 13000:3000
