name: Docker Compose CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debugging
        run: |
          docker version
          docker info
          docker images
          echo "Docker Hub Username: ${{ secrets.DOCKER_USERNAME }}"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t my-techdemo-app:${{ github.sha }} .

      - name: Tag Docker Image
        run: |
          docker tag my-techdemo-app:${{ github.sha }} localhost:5000/my-techdemo-app:${{ github.sha }}

      - name: Push Docker Image to Local Registry
        run: |
          docker push localhost:5000/my-techdemo-app:${{ github.sha }}
