name: Docker Compose CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debugging
        run: |
          docker version
          docker info
          docker images

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t my-techdemo-app:${{ github.sha }} .

      - name: Tag Docker Image
        run: |
          docker tag my-techdemo-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/my-techdemo-app:${{ github.sha }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-techdemo-app:${{ github.sha }}

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build
